site_name: 自己动手做聊天机器人
copyright: '版权 &copy; 2016 - 2017 shareditor.com'
pages:
  - 概述: index.md
  - 一-涉及知识: 1.knowledge.md
  - 二-初识NLTK库: 2.nltk.md
  - 三-语料与词汇资源: 3.corpus.md
  - 四-自动化词性标注: 4.pos-tagging.md
  - 五-文本分类: 5.text-classification.md
  - 六-结构化提取: 6.extract.md
  - 七-文法分析: 7.grammar.md
  - 八-自然语言处理: 8.nlp-review.md
  - 九-聊天机器人怎么做: 9.chatbot.md
  - 十-词性标注与关键词提取: 10.pos-ke.md
  - 十一-0字节存储海量语料资源: 11.storage.md
  - 十二-用语言云分析依存句法和语义依存: 12.semantic-dependency.md
  - 十三-探究语言模型: 13.linguistic-model.md
  - 十四-探究中文分词: 14.participles-art.md
  - 十五-概率图模型: 15.probabilistic-model.md
  - 十六-自然语言处理中的囊中取物: 16.bag-material.md
  - 十七-词性自动标注: 17.specific-mehtod.md
  - 十八-生成句法分析树: 18.tree.md
  - 十九-机器人是怎么理解“日后再说”的: 19.understand.md
  - 二十-语义角色标注: 20.pos-base-method.md
  - 二十一-隐含语义索引模型: 21.tf-idf.md
  - 二十二-人工神经网络: 22.artificial-neural-network.md
  - 二十三-用CNN做深度学习: 23.cnn.md
  - 二十四-将深度学习应用到NLP: 24.nlp-deep-learning.md
  - 二十五-word2vec的实现原理: 25.word2vec.md
  - 二十六-递归神经网络(RNN): 26.rnn.md
  - 二十七-自动问答: 27.auto-faq.md
  - 二十八-基于美剧字幕的聊天语料库建设: 28.subtitle-corpus.md
  - 二十九-近1GB的三千万聊天语料: 29.corpus-1g.md
  - 三十-第一版聊天机器人小二兔: 30.tiny-rabbit.md
  - 三十一-把网站流量导向小二兔: 31.directive.md
  - 三十二-用影视剧字幕语料库生成词向量: 32.word-vector.md
  - 三十三-LSTM-RNN—有记忆的神经网络: 33.lstm-rnn.md
  - 三十四-深度学习框架torch: 34.torch.md
  - 三十五-一学会甄嬛体: 35.lstm-learning.md
  - 三十六-tensorflow的session和graph: 36.tensorflow-session-graph.md
  - 三十七-tensorflow中的线性回归: 37.tensorflow-lr.md
  - 三十八-聊天机器人构建流程: 38.make-chatbot.md
  - 三十九-搭建一台GPU共享云服务: 39.gpu-server.md
  - 四十-视频之开篇宣言与知识点: 40.video-knowledge-point.md
  - 四十一-视频之环境搭建与python基础: 41.video-python.md
  - 四十二-从理论到实践开发聊天机器人1: 42.practice.md
  - 四十三-从理论到实践开发聊天机器人2: 43.practice2.md
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true